---
title: "clikr"
author: "Robert Reid"
date: "6/3/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(igraph)
theme_set(theme_bw())
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
mat <- matrix(c(1,1,2,3,3,4,5,5,6),nrow = 3)
name_list <- c("a","b","c")
dimnames(mat) <- list(name_list,name_list)

```

```{r}
biogrid__3_5_165 <- read_delim("data/biogrid/BIOGRID-ORGANISM-Saccharomyces_cerevisiae_S288c-3.5.165.tab2.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  #filter(`Experimental System` == "Negative Genetic") %>%
  select(
    geneA = `Official Symbol Interactor A`,
    geneB = `Official Symbol Interactor B`,
    orfA = `Systematic Name Interactor A`,
    orfB = `Systematic Name Interactor B`,
  )

```

Tally total interactions/gene as separate list


```{r}
# toy data
toy_frame <- read_csv("data/toy/toy-edges.csv")

# use edge list in dataframe to make graph
toy_graph <- graph_from_data_frame(toy_frame)

# plot graph
plot(toy_graph)

# make matrix of graph interactions
toy_mat <- as_adjacency_matrix(toy_graph, sparse = F)

# at this point can limit x and y to the nodes you want plotted (genes in screen)
# can also order them by some metric, such as rank or z score

# melt matrix to use in ploting routines
toy_data <- reshape2::melt(toy_mat)

toy_data2 <- reshape2::melt(toy_mat[c('a','b','r','s','t'),c('t','s','r','b','a')])

toy_data2 %>%
  ggplot(aes(x=Var1,y=Var2,fill=value)) +
  geom_raster() #+
  #scale_y_reverse()
```


Matrix approach

```{r}
# use edge list in dataframe to make graph
biogrid_graph <- graph_from_data_frame(biogrid__3_5_165[,3:4])

# plot graph
#plot(biogrid_graph) # takes forever

# make matrix of graph interactions
biogrid_mat <- as_adjacency_matrix(biogrid_graph, sparse = F)

# at this point can limit x and y to the nodes you want plotted (genes in screen)
# can also order them by some metric, such as rank or z score

#cispt <- readxl::read_excel("data/cisplatin/cisplatin data from Lee 2005.xlsx", 
    #skip = 1)
#write_csv(cispt,"data/cisplatin/lee-2005-cspt.csv")
cispt <- read_csv("data/cisplatin/lee-2005-cspt.csv")

# cispt$ORF already ordered by a screen set

# make sure screen ORFs are in biogrid set

biogrid_total <- unique(c(biogrid__3_5_165$orfA,biogrid__3_5_165$orfB))

ol <- cispt$ORF[which(cispt$ORF %in% biogrid_total)]

biogrid_experiment <- biogrid_mat[ol,ol]

# melt matrix to use in ploting routines
biogrid_data <- reshape2::melt(biogrid_experiment) %>%
  na_if(0)

#toy_data2 <- reshape2::melt(toy_mat[c('a','b','r','s','t'),c('t','s','r','b','a')])

biogrid_data %>%
  ggplot(aes(x=Var1,y=Var2,z=value)) +
  geom_bin2d() +
  #geom_raster(binwidth = 20, stat = "summary_2d", fun = sum, na.rm = TRUE) +
  #geom_hex(bins=200) +
  theme(axis.text.x = element_blank(),
    axis.text.y = element_blank()
  ) +
  scale_fill_viridis_c()

```



```{r}
# igraph examples

g <- sample_gnp(10, 2/10)
as_adjacency_matrix(g)
V(g)$name <- letters[1:vcount(g)]
as_adjacency_matrix(g)
E(g)$weight <- runif(ecount(g))
as_adjacency_matrix(g, attr="weight")

g_mat <- as_adj(g,sparse = F)


## A simple example with a couple of actors
## The typical case is that these tables are read in from files....
actors <- data.frame(name=c("Alice", "Bob", "Cecil", "David",
                            "Esmeralda"),
                     age=c(48,33,45,34,21),
                     gender=c("F","M","F","M","F"))
relations <- data.frame(from=c("Bob", "Cecil", "Cecil", "David",
                               "David", "Esmeralda"),
                        to=c("Alice", "Bob", "Alice", "Alice", "Bob", "Alice"),
                        same.dept=c(FALSE,FALSE,TRUE,FALSE,FALSE,TRUE),
                        friendship=c(4,5,5,2,1,1), advice=c(4,5,5,4,2,3))
g <- graph_from_data_frame(relations, directed=TRUE, vertices=actors)
print(g, e=TRUE, v=TRUE)

plot(g)

## The opposite operation
as_data_frame(g, what="vertices")
as_data_frame(g, what="edges")
```


## Rank order approach

This is similar to the Perl version of CLIK

```{r}
#cispt <- readxl::read_excel("data/cisplatin/cisplatin data from Lee 2005.xlsx", 
    #skip = 1)
#write_csv(cispt,"data/cisplatin/lee-2005-cspt.csv")
cispt <- read_csv("data/cisplatin/lee-2005-cspt.csv") %>%
  mutate(
    rank_a = row_number(),
    rank_b = rank_a
  )

# at this point should deal with duplicate data in a set and average the ranks

ranked_biogrid <- biogrid__3_5_165 %>%
  left_join(select(cispt,ORF,rank_a), by = c("orfA" = "ORF")) %>%
  left_join(select(cispt,ORF,rank_b), by = c("orfB" = "ORF"))

biogrid_trim <- ranked_biogrid[!is.na(ranked_biogrid$rank_a) | is.na(ranked_biogrid$rank_b),]

biogrid_trim %>%
  ggplot(aes(x=rank_a,y=rank_b)) +
  geom_point(size=0.05, alpha = 0.1) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank()
  )

biogrid_trim %>%
  ggplot(aes(x=rank_a,y=rank_b)) +
  geom_density2d() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank()
  )

```