---
title: "clikr - nsp4"
author: "Robert Reid"
date: "6/17/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
theme_set(theme_bw())
knitr::opts_chunk$set(echo = TRUE)
```

# Load BioGrid

- also need to write a BioGrid DL routine

```{r}
biogrid__3_5_165 <- read_delim("data/biogrid/BIOGRID-ORGANISM-Saccharomyces_cerevisiae_S288c-3.5.165.tab2.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  #filter(`Experimental System` == "Negative Genetic") %>%
  select(
    geneA = `Official Symbol Interactor A`,
    geneB = `Official Symbol Interactor B`,
    orfA = `Systematic Name Interactor A`,
    orfB = `Systematic Name Interactor B`,
  )
```

## Rank order approach

This is similar to the Perl version of CLIK

```{r}
# note this data is pre-sorted
orf8 <- read_csv("data/COVID/screenmill-interaction-scores-stringent-orf8.csv") %>%
  arrange(z_score) %>%
  mutate(
    strain_name = str_to_upper(strain_name),
    rank_a = row_number(),
    rank_b = rank_a
  )

# at this point should deal with duplicate data in a set and average the ranks

# CLIK graph interactions are set up on sorted experimental data

ranked_biogrid <- biogrid__3_5_165 %>%
  left_join(select(orf8,strain_name,rank_a), by = c("geneA" = "strain_name")) %>%
  left_join(select(orf8,strain_name,rank_b), by = c("geneB" = "strain_name")) %>%
  filter(complete.cases(.))


#pal <- viridisLite::magma(65,direction = -1)
#basePal <- colorRampPalette(pal)
basePal <- colorRampPalette(rainbow(65,start=0.35))
CLIK_colors <- densCols(ranked_biogrid$rank_a,ranked_biogrid$rank_b,
                        colramp=basePal,
                        nbin=132,
                        bandwidth = 18
                        )

ranked_biogrid %>%
  ggplot(aes(x=rank_a,y=rank_b)) +
  geom_point(size=0.05, alpha = 0.1, colour = CLIK_colors) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank()
  )

ranked_biogrid %>%
  ggplot(aes(x=rank_a,y=rank_b)) +
  geom_bin2d(bins=132) +
  scale_fill_viridis_c(direction = -1) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank()
  ) #+
  # xlim(c(1,200)) +
  # ylim(c(1,200))


ranked_biogrid %>%
  ggplot(aes(x=rank_a,y=rank_b)) +
  geom_density2d(n=132,h=18) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank()
  )

ranked_biogrid %>%
  ggplot(aes(x=rank_a,y=rank_b)) +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", colour="white",n=132,h=72) +
  #  geom_density2d(n=132,h=18) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank()
  ) #+
#  xlim(c(1,200)) +
#  ylim(c(1,200))


```